---
abstract: "Perl client to Datadog's dogstatsd metrics collector."
author:
  - 'Jennifer Pinkham <jpinkham@cpan.org>'
build_requires:
  Scalar::Util: '0'
  Storable: '0'
  Test::FailWarnings: '0'
  Test::Most: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Dogstatsd
provides:
  Net::Dogstatsd:
    file: lib/Net/Dogstatsd.pm
    version: v1.0.4
requires:
  Carp: '0'
  Data::Dumper: '0'
  Data::Validate::Type: '0'
  LWP::UserAgent: '0'
  Net::Telnet: '0'
  Try::Tiny: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/jpinkham/net-dogstatsd/issues
  homepage: https://metacpan.org/release/Net-Dogstatsd
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/jpinkham/net-dogstatsd
version: v1.0.4
